-- ============================================================
-- THPARFUMS — seed catalog (generated by scripts/gen-seed-sql.ts)
-- Run AFTER schema.sql. Re-running upserts products by slug; to fully
-- reset first run:  truncate public.products cascade;
-- Image URLs point at /products/*.jpg shipped in the app's public/ folder,
-- so no upload is needed for the seed. Admin uploads go to Storage.
-- ============================================================

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('afnan-9pm', '9PM', 'Afnan', 'Um dos árabes mais amados: doce, especiado e viciante, com excelente fixação e projeção para a noite.', 'masc', 'oriental', null, true, false, true, 1, '{"top":["Maçã","Lavanda","Canela"],"heart":["Âmbar","Orris"],"base":["Baunilha","Tonka","Madeiras"]}'::jsonb)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 13500, null, 'AFNAN9-50', 20),
    (100, 26900, null, 'AFNAN9-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p11.jpg', '9PM — Afnan', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('amber-empire', 'Amber Empire', 'French Avenue', 'Âmbar opulento e madeiras escuras. Presença marcante e sofisticada que não passa despercebida.', 'masc', 'amadeirado', null, true, false, true, 2, '{"top":["Pimenta rosa","Bergamota"],"heart":["Âmbar","Incenso"],"base":["Baunilha","Madeiras"]}'::jsonb)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 19500, null, 'AMBERE-50', 20),
    (100, 32900, null, 'AMBERE-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p01.jpg', 'Amber Empire — French Avenue', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('azure-aoud', 'Azzure Aoud', 'THPARFUMS', 'Oud refinado com um toque fresco e especiado. Masculino, encorpado e elegante.', 'masc', 'oriental', null, true, false, true, 3, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 16500, null, 'AZUREA-50', 20),
    (100, 32900, null, 'AZUREA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p03.jpg', 'Azzure Aoud — THPARFUMS', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('liquid-brun', 'Liquid Brun', 'THPARFUMS', 'Madeiras quentes e fumê com um fundo doce e resinoso. Intenso e viciante.', 'masc', 'amadeirado', null, true, false, true, 4, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 18000, null, 'LIQUID-50', 20),
    (100, 35900, null, 'LIQUID-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p09.jpg', 'Liquid Brun — THPARFUMS', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('royal-blend', 'Royal Blend', 'THPARFUMS', 'Mistura nobre de madeiras e especiarias. Sóbrio, versátil e de ótima fixação.', 'masc', 'amadeirado', null, false, false, true, 5, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 15000, null, 'ROYALB-50', 20),
    (100, 29900, null, 'ROYALB-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p06.jpg', 'Royal Blend — THPARFUMS', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('club-de-nuit-precieux', 'Club de Nuit Precieux', 'Armaf', 'Da aclamada linha Club de Nuit: âmbar, oud e especiarias em uma composição luxuosa e encorpada.', 'unisex', 'oriental', null, true, false, true, 6, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 23500, null, 'CLUBDE-50', 20),
    (100, 46900, null, 'CLUBDE-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p05.jpg', 'Club de Nuit Precieux — Armaf', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('badee-al-oud', 'Badee Al Oud', 'Lattafa', 'Oud aveludado com rosa e frutas escuras. Um clássico moderno de alta fixação.', 'unisex', 'oriental', null, true, false, true, 7, '{"top":["Frutas vermelhas"],"heart":["Oud","Rosa"],"base":["Âmbar","Madeiras"]}'::jsonb)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 17500, null, 'BADEEA-50', 20),
    (100, 34900, null, 'BADEEA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p04.jpg', 'Badee Al Oud — Lattafa', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('khamrah', 'Khamrah', 'Lattafa', 'Gourmand especiado: canela, tâmara e baunilha em um acorde quente e adocicado. Fenômeno de vendas.', 'unisex', 'oriental', null, true, true, true, 8, '{"top":["Canela","Noz-moscada","Bergamota"],"heart":["Tâmara","Praliné","Tuberosa"],"base":["Baunilha","Tonka","Benjoim"]}'::jsonb)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 14900, null, 'KHAMRA-50', 20),
    (100, 23900, null, 'KHAMRA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p10.jpg', 'Khamrah — Lattafa', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('royal-amber', 'Royal Amber', 'Orientica', 'Âmbar luxuoso e resinoso com madeiras nobres. Sofisticado, quente e de longuíssima duração.', 'unisex', 'oriental', null, true, false, true, 9, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 27500, null, 'ROYALA-50', 20),
    (100, 54900, null, 'ROYALA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p22.jpg', 'Royal Amber — Orientica', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('odyssey-marshmallow', 'Odyssey Marshmallow', 'Armaf', 'Doce e cremoso como marshmallow, com frutas e um fundo amadeirado. Confortável e cativante.', 'unisex', 'frutal', null, false, true, true, 10, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 17500, null, 'ODYSSE-50', 20),
    (100, 34900, null, 'ODYSSE-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p07.jpg', 'Odyssey Marshmallow — Armaf', 0, true),
    ('/products/p27.jpg', 'Odyssey Marshmallow — Armaf', 1, false)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('supremacy', 'Supremacy', 'Armaf', 'Encorpado e especiado, com madeiras e âmbar. Presença forte para ocasiões marcantes.', 'unisex', 'oriental', null, false, false, true, 11, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 16500, null, 'SUPREM-50', 20),
    (100, 32900, null, 'SUPREM-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p08.jpg', 'Supremacy — Armaf', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('abyad', 'Abyad', 'Al Wataniah', 'Flores brancas luminosas e limpas sobre um fundo amadeirado e suave. Elegante e versátil.', 'unisex', 'floral', null, false, false, true, 12, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 15000, null, 'ABYAD-50', 20),
    (100, 30000, null, 'ABYAD-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p30.jpg', 'Abyad — Al Wataniah', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('rayhaan', 'Rayhaan', 'Rasasi', 'Oriental encorpado com âmbar e especiarias. Quente, acolhedor e marcante.', 'unisex', 'oriental', null, false, false, true, 13, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 14500, null, 'RAYHAA-50', 20),
    (100, 28900, null, 'RAYHAA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p02.jpg', 'Rayhaan — Rasasi', 0, true),
    ('/products/p13.jpg', 'Rayhaan — Rasasi', 1, false)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('yara', 'Yara', 'Lattafa', 'Floral doce e cremoso com orquídea, heliotrópio e tâmara. Feminino, marcante e queridinho do público.', 'fem', 'floral', null, true, false, true, 14, '{"top":["Orquídea","Tâmara"],"heart":["Heliotrópio","Frutas tropicais"],"base":["Baunilha","Sândalo","Almíscar"]}'::jsonb)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 16000, null, 'YARA-50', 20),
    (100, 27000, null, 'YARA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p33.jpg', 'Yara — Lattafa', 0, true),
    ('/products/p34.jpg', 'Yara — Lattafa', 1, false)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('eclaire', 'Eclaire', 'Lattafa', 'Gourmand luminoso e doce, com caramelo, frutas e flores. Festivo e envolvente.', 'fem', 'floral', null, true, true, true, 15, '{"top":["Frutas vermelhas","Pêra"],"heart":["Caramelo","Flor de laranjeira"],"base":["Baunilha","Tonka"]}'::jsonb)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 17500, null, 'ECLAIR-50', 20),
    (100, 34900, null, 'ECLAIR-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p14.jpg', 'Eclaire — Lattafa', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('mayar', 'Mayar', 'Lattafa', 'Floral frutado radiante, suave e elegante. Delicado para o dia a dia com toque de sofisticação.', 'fem', 'floral', null, true, false, true, 16, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 18000, null, 'MAYAR-50', 20),
    (100, 36000, null, 'MAYAR-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p20.jpg', 'Mayar — Lattafa', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('athena', 'Athena', 'Maison Alhambra', 'Floral branco luminoso e sofisticado, com lírio-do-vale e baunilha. Elegância atemporal.', 'fem', 'floral', null, true, true, true, 17, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 16500, null, 'ATHENA-50', 20),
    (100, 33000, null, 'ATHENA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p19.jpg', 'Athena — Maison Alhambra', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('club-de-nuit-maleka', 'Club de Nuit Maleka', 'Armaf', 'Floral frutado opulento e feminino da linha Club de Nuit. Marcante, doce e de ótima fixação.', 'fem', 'floral', null, true, false, true, 18, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 19000, null, 'CLUBDE-50', 20),
    (100, 37900, null, 'CLUBDE-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p24.jpg', 'Club de Nuit Maleka — Armaf', 0, true),
    ('/products/p25.jpg', 'Club de Nuit Maleka — Armaf', 1, false)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('ajwad', 'Ajwad', 'Lattafa', 'Floral frutado refinado e doce, com frutas vermelhas e baunilha. Versátil e elegante.', 'fem', 'floral', null, false, true, true, 19, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 16500, null, 'AJWAD-50', 20),
    (100, 27400, null, 'AJWAD-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p12.jpg', 'Ajwad — Lattafa', 0, true),
    ('/products/p17.jpg', 'Ajwad — Lattafa', 1, false)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('watani', 'Watani', 'Al Wataniah', 'Buquê floral encorpado e marcante, com fundo quente. Feminino e sofisticado.', 'fem', 'floral', null, false, false, true, 20, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 15000, null, 'WATANI-50', 20),
    (100, 30000, null, 'WATANI-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p15.jpg', 'Watani — Al Wataniah', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('sabah-al-ward', 'Sabah Al Ward', 'Al Wataniah', 'Rosas e flores luminosas em uma composição doce e elegante. Romântico e duradouro.', 'fem', 'floral', null, false, false, true, 21, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 14500, null, 'SABAHA-50', 20),
    (100, 28900, null, 'SABAHA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p16.jpg', 'Sabah Al Ward — Al Wataniah', 0, true),
    ('/products/p23.jpg', 'Sabah Al Ward — Al Wataniah', 1, false),
    ('/products/p29.jpg', 'Sabah Al Ward — Al Wataniah', 2, false)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('ameerati', 'Ameerati', 'Al Wataniah', 'Oriental doce e acolhedor, com baunilha e âmbar. Confortável e marcante por um ótimo custo.', 'fem', 'oriental', null, false, false, true, 22, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 8000, null, 'AMEERA-50', 20),
    (100, 16000, null, 'AMEERA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p18.jpg', 'Ameerati — Al Wataniah', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('reyna', 'Reyna', 'Al Wataniah', 'Floral elegante e luminoso, suave e feminino. Perfeito para o dia a dia.', 'fem', 'floral', null, false, false, true, 23, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 14500, null, 'REYNA-50', 20),
    (100, 29000, null, 'REYNA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p31.jpg', 'Reyna — Al Wataniah', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('pretty-in-pink', 'Pretty in Pink', 'Rayhaan', 'Floral frutado alegre e doce, jovem e cativante. Leve e charmoso.', 'fem', 'floral', null, false, false, true, 24, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 14500, null, 'PRETTY-50', 20),
    (100, 28900, null, 'PRETTY-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p26.jpg', 'Pretty in Pink — Rayhaan', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('noble-blush', 'Badee Al Oud Noble Blush', 'Lattafa', 'Da linha Badee Al Oud: frutas vermelhas, rosa e oud em um acorde feminino, doce e encorpado.', 'fem', 'oriental', null, false, true, true, 25, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 16500, null, 'NOBLEB-50', 20),
    (100, 33000, null, 'NOBLEB-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p32.jpg', 'Badee Al Oud Noble Blush — Lattafa', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('ck-one-shock-her', 'CK One Shock For Her', 'Calvin Klein', 'Designer original: frutado e floral com fundo amadeirado adocicado. Moderno e sensual.', 'fem', 'frutal', null, false, false, true, 26, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 24500, null, 'CKONES-50', 20),
    (100, 49000, null, 'CKONES-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p21.jpg', 'CK One Shock For Her — Calvin Klein', 0, true)
) as d(url, alt, sort, is_primary);

with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    ('jpg-scandal', 'Scandal', 'Jean Paul Gaultier', 'Designer original: mel, gardênia e patchouli em um gourmand floral marcante e sedutor.', 'fem', 'oriental', null, false, false, true, 27, null)
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
    (50, 24500, null, 'JPGSCA-50', 20),
    (100, 49000, null, 'JPGSCA-100', 20)
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
    ('/products/p28.jpg', 'Scandal — Jean Paul Gaultier', 0, true)
) as d(url, alt, sort, is_primary);
