/**
 * Generates supabase/seed.sql from the canonical SEED_PRODUCTS data so the DB
 * seed never drifts from the local-fallback catalog.
 *   npx tsx scripts/gen-seed-sql.ts
 */
import { writeFileSync } from "node:fs";
import { SEED_PRODUCTS } from "../src/data/seed";

const s = (v: string | null | undefined) =>
  v == null ? "null" : `'${v.replace(/'/g, "''")}'`;
const n = (v: number | null | undefined) => (v == null ? "null" : String(v));
const b = (v: boolean) => (v ? "true" : "false");
const jsonb = (v: unknown) =>
  v == null ? "null" : `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;

const blocks = SEED_PRODUCTS.map((p) => {
  const variantRows = p.variants
    .map(
      (v) =>
        `    (${n(v.volume_ml)}, ${n(v.price_cents)}, ${n(
          v.sale_price_cents,
        )}, ${s(v.sku)}, ${n(v.stock)})`,
    )
    .join(",\n");

  const imageRows = p.images
    .map(
      (img) =>
        `    (${s(img.url)}, ${s(img.alt)}, ${n(img.sort)}, ${b(
          img.is_primary,
        )})`,
    )
    .join(",\n");

  return `with prod as (
  insert into public.products
    (slug, name, brand, description, gender, family, inspired_by, is_featured, is_new, is_active, sort, notes)
  values
    (${s(p.slug)}, ${s(p.name)}, ${s(p.brand)}, ${s(p.description)}, ${s(
      p.gender,
    )}, ${s(p.family)}, ${s(p.inspired_by)}, ${b(p.is_featured)}, ${b(
      p.is_new,
    )}, ${b(p.is_active)}, ${n(p.sort)}, ${jsonb(p.notes)})
  on conflict (slug) do update set name = excluded.name
  returning id
),
ins_variants as (
  insert into public.product_variants
    (product_id, volume_ml, price_cents, sale_price_cents, sku, stock)
  select prod.id, d.volume_ml::int, d.price_cents::int, d.sale_price_cents::int, d.sku, d.stock::int
  from prod, (values
${variantRows}
  ) as d(volume_ml, price_cents, sale_price_cents, sku, stock)
  returning 1
)
insert into public.product_images (product_id, url, alt, sort, is_primary)
select prod.id, d.url, d.alt, d.sort, d.is_primary
from prod, (values
${imageRows}
) as d(url, alt, sort, is_primary);`;
});

const out = `-- ============================================================
-- THPARFUMS — seed catalog (generated by scripts/gen-seed-sql.ts)
-- Run AFTER schema.sql. Re-running upserts products by slug; to fully
-- reset first run:  truncate public.products cascade;
-- Image URLs point at /products/*.jpg shipped in the app's public/ folder,
-- so no upload is needed for the seed. Admin uploads go to Storage.
-- ============================================================

${blocks.join("\n\n")}
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out);
console.log(
  `Wrote supabase/seed.sql (${SEED_PRODUCTS.length} products, ${SEED_PRODUCTS.reduce(
    (a, p) => a + p.variants.length,
    0,
  )} variants).`,
);
